config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to: "posts#index"
  resources :posts do
    resource :likes, only: [:create, :destroy]
    resource :comments, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  resources :users, only: [:show] do
    member do
      get :follows, :followers
    end
    resource :relationships, only: [:create, :destroy]
  end
  resources :categories, only: [:index]
  resources :brands, only: [:index]
  get '/posts/category/:id', to: "posts#category"
  get '/posts/brand/:id', to: "posts#brand"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @post_like = Like.new(user_id: current_user.id, post_id: params[:post_id])
    @post_like.save
  end

  def destroy
    @post = Post.find(params[:post_id])
    @post_like = Like.find_by(user_id: current_user.id, post_id: params[:post_id])
    @post_like.destroy
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_likes.html.erb
<% if post.liked?(current_user) %>
  <%= link_to post_likes_path(post.id), method: :delete, remote: true, class:"text-decoration-none text-reset" do %>
    <i class="fa-solid fa-lg fa-heart" style="color:gold"></i>
    <a><%= post.likes.count %></a>
  <% end %>
<% else %>
  <%= link_to post_likes_path(post.id), method: :post, remote: true, class:"text-decoration-none text-reset" do %>
    <i class="fa-regular fa-lg fa-heart"></i>
    <%= post.likes.count %>
  <% end %>
<% end %>

app/views/likes/create.js.erb
$('#like_buttons_<%= @post.id %>').html("<%= j(render "likes/likes", post: @post) %>");

app/views/likes/destroy.js.erb
$('#like_buttons_<%= @post.id %>').html("<%= j(render "likes/likes", post: @post) %>");