config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to: "posts#index"
  resources :posts do
    resource :likes, only: [:create, :destroy]
    resource :comments, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  resources :users, only: [:show] do
    member do
      get :follows, :followers
    end
    resource :relationships, only: [:create, :destroy]
  end
  resources :categories, only: [:index]
  resources :brands, only: [:index]
  get '/posts/category/:id', to: "posts#category"
  get '/posts/brand/:id', to: "posts#brand"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: 'には英字と数字の両方を含めて設定してください', allow_blank: true

  validates :nickname, presence: true

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_posts, through: :likes, source: :post
  has_many :follower, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :followed, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower

  # extend ActiveHash::Associations::ActiveRecordExtensions
  # belongs_to :prefecture

  def liked_by?(post_id)
    likes.where(post_id: post_id).exists?
  end

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  def update
    super
    resource.avatar.attach(account_update_params[:avatar]) if account_update_params[:avatar].present?
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).reverse_order
    @posts1 = @user.posts.where(user_id: @user.id, category_id: [2, 3, 4]).order(updated_at: :desc)
    @posts2 = @user.posts.where(user_id: @user.id, category_id: [5, 6, 7, 8, 9, 10, 11]).order(updated_at: :desc)
    @posts3 = @user.posts.where(user_id: @user.id, category_id: [12, 13, 14, 15]).order(updated_at: :desc)
    @posts4 = @user.posts.where(user_id: @user.id,
                                category_id: [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
                                              29, 30]).order(updated_at: :desc)
    @posts5 = @user.posts.where(user_id: @user.id, category_id: [31, 32, 33, 34, 35]).order(updated_at: :desc)
    @posts6 = @user.posts.where(user_id: @user.id, category_id: [36, 37, 38, 39, 40]).order(updated_at: :desc)
    @posts7 = @user.posts.where(user_id: @user.id, category_id: [41, 42, 43, 44]).order(updated_at: :desc)
    @posts8 = @user.posts.where(user_id: @user.id, category_id: [45, 46, 47, 48, 49, 50, 51, 52, 53]).order(updated_at: :desc)
    @posts9 = @user.posts.where(user_id: @user.id, category_id: [54, 55, 56]).order(updated_at: :desc)
    @posts10 = @user.posts.where(user_id: @user.id, category_id: [57, 58, 59]).order(updated_at: :desc)
    @posts11 = @user.posts.where(user_id: @user.id, category_id: [60]).order(updated_at: :desc)
    @posts12 = @user.posts.where(user_id: @user.id, category_id: [61]).order(updated_at: :desc)
    @posts13 = @user.posts.where(user_id: @user.id, category_id: [62]).order(updated_at: :desc)
    @posts14 = @user.posts.where(user_id: @user.id, category_id: [63, 64, 65]).order(updated_at: :desc)
    @following_users = @user.following_user
    @follower_users = @user.follower_user
  end

  def follows
    @user = User.find(params[:id])
    @users = @user.following_user.reverse_order
    @following_users = @user.following_user
    @follower_users = @user.follower_user
    @posts = @user.posts.page(params[:page]).reverse_order
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.follower_user.reverse_order
    @following_users = @user.following_user
    @follower_users = @user.follower_user
    @posts = @user.posts.page(params[:page]).reverse_order
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/followers.html.erb
<%= render "shared/header" %>

  <main>
    <div class="container-fluid bg-light">
      <div class="card w-90 p-0 mx-auto shadow-sm">
        <div class="card-body">
          <h4 class="text-center py-3 bg-light border"><%= @user.nickname %>さんのフォロワー一覧</h4>

          <div class="text-center bg-light p-3 mb-2">
            <% if @user.avatar.attached? %>
              <%= image_tag @user.avatar, size: "64x64", class:"rounded-circle img-fluid" %>
            <% else %>
              <%= image_tag "noavatar.png", size: "64x64", class:"rounded-circle img-fluid" %>
            <% end %>
            <p class="d-flex justify-content-end">
            <% if user_signed_in? %>
              <% if user_signed_in? && @user == current_user %>
                <%= link_to "ユーザー情報編集", edit_user_registration_path, class: "mt-2 mx-auto btn-sm btn-secondary" %> 
              <% end %>
              <% if current_user != @user %>
                <% if current_user.following?(@user) %>
                  <%= link_to 'フォローを外す', user_relationships_path(@user.id), method: :delete, class: "mt-2 mx-auto btn-sm btn-link" %>
                <% else %>
                  <%= link_to 'フォローする', user_relationships_path(@user.id), method: :POST, class:"mt-2 mx-auto btn-sm btn-secondary" %>
                <% end %>
              <% end %>
            <% end %>
            </p>
            <div>
            <%= link_to follows_user_path(@user), class:"link-dark" do %>
            フォロー数: <%= @following_users.count %>人
            <% end %> 
            <%= link_to followers_user_path(@user), class: "link-dark" do %>
            フォロワー数: <%= @follower_users.count %>人
            <% end %>
            </div>
            <div>
            登録ギア数: <%= @posts.count %>個
            </div>
          </div>

          <div class="album pb-3 mb-2 bg-light">
            <h5 class="text-center py-3 bg-light">フォローされているユーザー</h5>
            <div class="container">
              <div class="row row-cols-12 row-cols-xs-3 row-cols-sm-3 row-cols-md-6 g-3">
                <% @users.each do |user| %>
                <div class="col">
                  <div class="card shadow-sm">
                    <% if user.avatar.attached? %>
                      <%= image_tag user.avatar, size: "200x200", class: "img-fluid post-img" %>
                    <% else %>
                      <%= image_tag "noavatar.png", size: "200x200", class: "img-fluid post-img" %>
                    <% end %>
                    <div class="card-body">
                      <div class="justify-content-between align-items-center">
                        <div><%= link_to user.nickname, user_path(user.id), class:"small text-muted" %></div>
                      </div>
                    </div>
                  </div>
                </div>
                <% end %>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  </main>

<%= render "shared/footer" %>

app/views/users/follows.html.erb
<%= render "shared/header" %>

  <main>
    <div class="container-fluid bg-light">
      <div class="card w-90 p-0 mx-auto shadow-sm">
        <div class="card-body">
          <h4 class="text-center py-3 bg-light border"><%= @user.nickname %>さんのフォロー一覧</h4>

          <div class="text-center bg-light p-3 mb-2">
            <% if @user.avatar.attached? %>
              <%= image_tag @user.avatar, size: "64x64", class:"rounded-circle img-fluid" %>
            <% else %>
              <%= image_tag "noavatar.png", size: "64x64", class:"rounded-circle img-fluid" %>
            <% end %>
            <p class="d-flex justify-content-end">
            <% if user_signed_in? %>
              <% if user_signed_in? && @user == current_user %>
                <%= link_to "ユーザー情報編集", edit_user_registration_path, class: "mt-2 mx-auto btn-sm btn-secondary" %> 
              <% end %>
              <% if current_user != @user %>
                <% if current_user.following?(@user) %>
                  <%= link_to 'フォローを外す', user_relationships_path(@user.id), method: :delete, class: "mt-2 mx-auto btn-sm btn-link" %>
                <% else %>
                  <%= link_to 'フォローする', user_relationships_path(@user.id), method: :POST, class:"mt-2 mx-auto btn-sm btn-secondary" %>
                <% end %>
              <% end %>
            <% end %>
            </p>
            <div>
            <%= link_to follows_user_path(@user), class:"link-dark" do %>
            フォロー数: <%= @following_users.count %>人
            <% end %> 
            <%= link_to followers_user_path(@user), class: "link-dark" do %>
            フォロワー数: <%= @follower_users.count %>人
            <% end %>
            </div>
            <div>
            登録ギア数: <%= @posts.count %>個
            </div>
          </div>

          <div class="album pb-3 mb-2 bg-light">
            <h5 class="text-center py-3 bg-light">フォローしているユーザー</h5>
            <div class="container">
              <div class="row row-cols-12 row-cols-xs-3 row-cols-sm-3 row-cols-md-6 g-3">
                <% @users.each do |user| %>
                <div class="col">
                  <div class="card shadow-sm">
                    <% if user.avatar.attached? %>
                      <%= image_tag user.avatar, size: "200x200", class: "img-fluid post-img" %>
                    <% else %>
                      <%= image_tag "noavatar.png", size: "200x200", class: "img-fluid post-img" %>
                    <% end %>
                    <div class="card-body">
                      <div class="justify-content-between align-items-center">
                        <div><%= link_to user.nickname, user_path(user.id), class:"small text-muted" %></div>
                      </div>
                    </div>
                  </div>
                </div>
                <% end %>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  </main>

<%= render "shared/footer" %>

app/views/users/show.html.erb
<%= render "shared/header" %>

  <main>
    <div class="container-fluid bg-light">
      <div class="card w-90 p-0 mx-auto shadow-sm">
        <div class="card-body">
          <h4 class="text-center py-3 bg-light border fw-bold"><%= @user.nickname %>さんのマイページ</h4>

          <div class="text-center bg-light p-3 mb-2">
            <% if @user.avatar.attached? %>
              <%= image_tag @user.avatar, size: "64x64", class:"img-thumbnail img-fluid" %>
            <% else %>
              <%= image_tag "noavatar.png", size: "128x128", class:"img-thumbnail img-fluid" %>
            <% end %><br>
            <p class="d-flex justify-content-end">
            <% if user_signed_in? %>
              <% if user_signed_in? && @user == current_user %>
                <%= link_to "ユーザー情報編集", edit_user_registration_path, class: "mt-2 mx-auto btn-sm btn-secondary" %> 
              <% end %>
              <% if current_user != @user %>
                <% if current_user.following?(@user) %>
                  <%= link_to 'フォローを外す', user_relationships_path(@user.id), method: :delete, class: "mt-2 mx-auto btn-sm btn-link" %>
                <% else %>
                  <%= link_to 'フォローする', user_relationships_path(@user.id), method: :POST, class:"mt-2 mx-auto btn-sm btn-secondary" %>
                <% end %>
              <% end %>
            <% end %>
            </p>
            キャンパーランク: <%= @user.rank_name %><br>
            キャンパーExp: <%= @user.exp_point %>P<br>
            <%= image_tag "rank/#{@user.rank}.png", size: "64x64", class:"rounded-circle bg-white shadow" %><br>

            <div>
            <%= link_to follows_user_path(@user), class:"link-dark" do %>
            フォロー数: <%= @following_users.count %>人
            <% end %> 
            <%= link_to followers_user_path(@user), class: "link-dark" do %>
            フォロワー数: <%= @follower_users.count %>人
            <% end %>
            </div>
            <div>
            登録ギア数: <%= @posts.count %>個
            </div>
          </div>

          <div class="album pb-3 mb-2 bg-light">
            <h5 class="text-center py-3 bg-light">テント/タープ</h5>
            <div class="container">
              <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                <% @posts1.each do |post| %>
                  <%= render "shared/albumdetail", post: post %>
                <% end %>
              </div>
            </div>
          </div>
          
          <div class="album pb-3 mb-2 bg-light">
            <h5 class="text-center py-3 bg-light">寝具</h5>
            <div class="container">
              <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                <% @posts2.each do |post| %>
                  <%= render "shared/albumdetail", post: post %>
                <% end %>
              </div>
            </div>
          </div>

          <div class="album pb-3 mb-2 bg-light">
            <h5 class="text-center py-3 bg-light">クーラーボックス</h5>
            <div class="container">
              <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                <% @posts3.each do |post| %>
                  <%= render "shared/albumdetail", post: post %>
                <% end %>
              </div>
            </div>
          </div>

          <div class="album pb-3 mb-2 bg-light">
            <h5 class="text-center py-3 bg-light">調理器具</h5>
            <div class="container">
              <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                <% @posts4.each do |post| %>
                  <%= render "shared/albumdetail", post: post %>
                <% end %>
              </div>
            </div>
          </div>

          <div class="album pb-3 mb-2 bg-light">
            <h5 class="text-center py-3 bg-light">燃料/着火用具</h5>
            <div class="container">
              <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                <% @posts5.each do |post| %>
                  <%= render "shared/albumdetail", post: post %>
                <% end %>
              </div>
            </div>
          </div>

          <div class="album pb-3 mb-2 bg-light">
            <h5 class="text-center py-3 bg-light">テーブルウェア(食器)</h5>
            <div class="container">
              <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                <% @posts6.each do |post| %>
                  <%= render "shared/albumdetail", post: post %>
                <% end %>
              </div>
            </div>
          </div>

          <div class="album pb-3 mb-2 bg-light">
            <h5 class="text-center py-3 bg-light">ファーニチャー</h5>
            <div class="container">
              <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                <% @posts7.each do |post| %>
                  <%= render "shared/albumdetail", post: post %>
                <% end %>
              </div>
            </div>
          </div>

          <div class="album pb-3 mb-2 bg-light">
            <h5 class="text-center py-3 bg-light">ライト/ランタン</h5>
            <div class="container">
              <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                <% @posts8.each do |post| %>
                  <%= render "shared/albumdetail", post: post %>
                <% end %>
              </div>
            </div>
          </div>

          <div class="album pb-3 mb-2 bg-light">
            <h5 class="text-center py-3 bg-light">暖房器具(ストーブ/ヒーター)</h5>
            <div class="container">
              <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                <% @posts9.each do |post| %>
                  <%= render "shared/albumdetail", post: post %>
                <% end %>
              </div>
            </div>
          </div>

          <div class="album pb-3 mb-2 bg-light">
            <h5 class="text-center py-3 bg-light">収納ボックス/収納ラック</h5>
            <div class="container">
              <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                <% @posts10.each do |post| %>
                  <%= render "shared/albumdetail", post: post %>
                <% end %>
              </div>
            </div>
          </div>

          <div class="album pb-3 mb-2 bg-light">
            <h5 class="text-center py-3 bg-light">キャリー/カート</h5>
            <div class="container">
              <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                <% @posts11.each do |post| %>
                  <%= render "shared/albumdetail", post: post %>
                <% end %>
              </div>
            </div>
          </div>

          <div class="album pb-3 mb-2 bg-light">
            <h5 class="text-center py-3 bg-light">サーキュレーター</h5>
            <div class="container">
              <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                <% @posts12.each do |post| %>
                  <%= render "shared/albumdetail", post: post %>
                <% end %>
              </div>
            </div>
          </div>

          <div class="album pb-3 mb-2 bg-light">
            <h5 class="text-center py-3 bg-light">ポータブル電源</h5>
            <div class="container">
              <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                <% @posts13.each do |post| %>
                  <%= render "shared/albumdetail", post: post %>
                <% end %>
              </div>
            </div>
          </div>

          <div class="album pb-3 mb-2 bg-light">
            <h5 class="text-center py-3 bg-light">その他キャンプ用品</h5>
            <div class="container">
              <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                <% @posts14.each do |post| %>
                  <%= render "shared/albumdetail", post: post %>
                <% end %>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  </main>

<%= render "shared/footer" %>