config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to: "posts#index"
  resources :posts do
    resource :likes, only: [:create, :destroy]
    resource :comments, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  resources :users, only: [:show] do
    member do
      get :follows, :followers
    end
    resource :relationships, only: [:create, :destroy]
  end
  resources :categories, only: [:index]
  resources :brands, only: [:index]
  get '/posts/category/:id', to: "posts#category"
  get '/posts/brand/:id', to: "posts#brand"
end

app/views/shared/_album.html.erb
<div class="container">
  <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    <% @posts.each do |post| %>
      <%= render "shared/albumdetail", post: post %>
    <% end %>
  </div>
</div>

app/views/shared/_albumdetail.html.erb
<div class="col">
  <div class="card shadow-sm">
    <% if post.image.present? %>
      <%= link_to image_tag(post.image, class: "w-100 rounded-top post-img img-fulid"), post_path(post.id) %>
    <% else %>
      <%= link_to image_tag("nophoto.png", class: "w-100 rounded-top post-img img-fulid"), post_path(post.id) %>
    <% end %>
    <div class="card-body">
      <p><small>
        <%= link_to post.brand.name, "/posts/brand/#{post.brand_id}", class:"text-muted" %> > 
        <%= link_to post.category.name, "/posts/category/#{post.category_id}", class:"text-muted" %>
      </small></p>
      <h5><%= link_to post.gearmodel, post_path(post.id), class:"text-decoration-none text-reset" %></h5>
      <p class="card-text"><%= post.text.truncate(30) %></p>
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
        
          <% if user_signed_in? %>
            <button type="button" class="btn btn-sm btn-outline-secondary">
              <div id="like_buttons_<%= post.id %>">
              <%= render "likes/likes", post: post %>
              </div>
            </button> 
          <% else %>
            <button type="button" class="btn btn-sm btn-outline-secondary">
              <i class="fa-regular fa-lg fa-heart"></i>
              <a><%= post.likes.count %></a>
            </button> 
          <% end %>

          <button type="button" class="btn btn-sm btn-outline-secondary">
            <%= link_to post_path(post.id, anchor:'comments'), class:'text-decoration-none text-reset' do %>
              <i class="fa-regular fa-lg fa-message"></i>
              <a><%= post.comments.count %></a>
            <% end %>
          </button>
          
        </div>
        <small><%= image_tag "rank/#{post.user.rank}.png", size: "32x32", class:"rounded-circle shadow" %>
        <%= link_to post.user.nickname.truncate(18), user_path(post.user.id), class:"text-muted" %></small>
      </div>
    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="text-muted py-2">
  <div class="container">
    <p class="float-end mb-1">
      <a href="#", class="text-muted">Back to top</a>
    </p>
    <p class="mb-1">&copy; 2022 troymich123</p>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="p-1 mb-2 border-bottom bg-white">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <%= link_to image_tag("logo.png", size: "110x64", class:"img-fluid rounded-3"), "/" %>

      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li><a href="/categories" class="nav-link px-2 link-dark">カテゴリー</a></li>
        <li><a href="/brands" class="nav-link px-2 link-dark">ブランド</a></li>
      </ul>

      <div class="col-8 col-lg-auto mb-3 mb-lg-0 me-lg-3">
        <%= search_form_for @search, url: search_posts_path do |f| %>
          <%= f.text_field :gearmodel_or_text_cont, placeholder: 'ギア検索...', class:"form-control" %>
        <% end %>
      </div>

      <div class="col-2 col-lg-auto mb-3 mb-lg-0 me-md-3 dropdown text-end">
        <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1" data-toggle="dropdown" aria-expanded="false">
          <% if user_signed_in? && @myuser.avatar.attached? %>
            <%= image_tag @myuser.avatar, size: "32x32", class:"mx-auto rounded-circle" %>
          <% elsif user_signed_in? %>
            <%= image_tag "noavatar.png", size: "32x32", class:"mx-auto rounded-circle" %>
          <% else %>
            <%= image_tag "notsignedin.jpg", size: "32x32", class:"mx-auto rounded-circle" %>
          <% end %>
        </a>
        <ul class="dropdown-menu dropdown-menu-right text-small" aria-labelledby="dropdownUser1">
          <% if user_signed_in? %>
            <li><%= link_to 'ギア登録', new_post_path, class: "dropdown-item" %></li>
            <li><%= link_to 'マイページ', user_path(current_user.id), class: "dropdown-item" %></li>
            <li><%= link_to 'フォローしているユーザー', follows_user_path(@myuser), class: "dropdown-item" %></li>
            <li><%= link_to 'ユーザー情報編集', edit_user_registration_path, class:'dropdown-item' %></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "dropdown-item" %></li>
          <% else %>
            <li><%= link_to 'ログイン', new_user_session_path, class: "dropdown-item" %></li>
            <li><%= link_to 'ユーザー登録', new_user_registration_path, class: "dropdown-item" %></li>
          <% end %>
        </ul>
      </div>

      <div class="bg-light mb-3 mb-lg-0 me-lg-3">
        <form class="form-inline">
          <button class="btn btn-secondary" type="button">
            <%= link_to "ギア登録", new_post_path, class:'text-decoration-none text-reset' %>
          </button>
        </form>
      </div>

    </div>
  </div>
</header>