config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to: "posts#index"
  resources :posts do
    resource :likes, only: [:create, :destroy]
    resource :comments, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  resources :users, only: [:show] do
    member do
      get :follows, :followers
    end
    resource :relationships, only: [:create, :destroy]
  end
  resources :categories, only: [:index]
  resources :brands, only: [:index]
  get '/posts/category/:id', to: "posts#category"
  get '/posts/brand/:id', to: "posts#brand"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :like_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
  belongs_to :brand
  has_one_attached :image

  with_options presence: true, numericality: { other_than: 1, message: 'を入力してください' } do
    validates :category_id
    validates :brand_id
  end
  validates :gearmodel, presence: true, length: { maximum: 40 }
  validates :text, presence: true, length: { maximum: 1000 }

  def liked?(user)
    likes.where(user_id: user.id).exists?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :redirect_root, only: [:edit, :destroy]

  def index
    @posts = Post.all.includes(:likes).order(updated_at: :desc).page(params[:page]).per(6)
    @posts_best = Post.all.includes(:likes).sort { |a, b| b.likes.size <=> a.likes.size }
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      # 経験値アップ・レベルアップ機能
      user = User.find(current_user.id)
      user.exp_point = user.exp_point + 1
      user.update(exp_point: user.exp_point)
      if user.rank < 26
        ranksetting = RankSetting.find_by(rank: user.rank + 1)
        if ranksetting.threshold <= user.exp_point
          user.rank = user.rank + 1
          user.rank_name = ranksetting.rank_name
          user.update(rank: user.rank, rank_name: user.rank_name)
        end
      end
      # /経験値アップ・レベルアップ機能
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.order(id: 'DESC')
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to post_path
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    # 経験値ダウン・レベルダウン機能
    user = User.find(current_user.id)
    user.exp_point = user.exp_point - 1
    user.update(exp_point: user.exp_point)
    if user.rank > 1
      ranksetting = RankSetting.find_by(rank: user.rank - 1)
      if ranksetting.threshold <= user.exp_point
        user.rank = user.rank - 1
        user.rank_name = ranksetting.rank_name
        user.update(rank: user.rank, rank_name: user.rank_name)
      end
    end
    # /経験値ダウン・レベルダウン機能
    redirect_to root_path
  end

  def category
    @post = Post.find_by(category_id: params[:id])
    @posts = Post.where(category_id: params[:id]).order(created_at: 'DESC')
  end

  def brand
    @post = Post.find_by(brand_id: params[:id])
    @posts = Post.where(brand_id: params[:id]).order('created_at DESC')
  end

  private

  def post_params
    params.require(:post).permit(:category_id, :brand_id, :gearmodel, :text, :image, :price, :url, :purchase_date, :release_date).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def redirect_root
    redirect_to root_path unless user_signed_in? && current_user.id == @post.user_id
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/brand.html.erb
<%= render "shared/header" %>

  <main>
    <div class="text-center container-fluid bg-light">
      <div class="card w-90 p-0 mx-auto shadow-sm">
        <div class="card-body">

          <% if @post.present? %>
            <h4 class="text-center mt-2 py-3 bg-light"><%= @post.brand.name %> 投稿一覧</h4>
          <% end %>

          <div class="album py-3 bg-light">
            <%= render "shared/album" %>
          </div>

        </div>
      </div>
    </div>
  </main>

<%= render "shared/footer" %>

app/views/posts/category.html.erb
<%= render "shared/header" %>

  <main>
    <div class="text-center container-fluid bg-light">
      <div class="card w-90 p-0 mx-auto shadow-sm">
        <div class="card-body">
        
          <% if @post.present? %>
            <h4 class="text-center mt-2 py-3 bg-light"><%= @post.category.name %> 投稿一覧</h4>
          <% end %>

          <div class="album py-3 bg-light">
            <%= render "shared/album" %>
          </div>

        </div>
      </div>
    </div>
  </main>

<%= render "shared/footer" %>

app/views/posts/edit.html.erb
<%= render "shared/header" %>

  <main>
    <div class="container-fluid text-center py-3 bg-light">
      <div class="col-lg-6 card mb-3 w-90 p-4 mx-auto shadow-sm">

        <%= form_with model: @post, local: true do |f| %>
          <%= render 'shared/error_messages', model: f.object %>

          <% if @post.image.present? %>
            <%= image_tag @post.image, class: "mx-auto rounded w-75 img-fluid" %>
          <% else %>
            <%= image_tag "nophoto.png", size:"300x200", class: "mx-auto rounded w-75 img-fluid" %>
          <% end %>
          <div class="img-upload">
            <div class="click-upload">
              <label for="gearimagepost">ギア画像</label>
              <%= f.file_field :image, class:"form-control", id:"gearimagepost" %>
            </div>
          </div>

          <div class="inputcategory">
            <label for="inputcategory">カテゴリー*</label>
            <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"form-control", id:"inputcategory"}) %>
          </div>

          <div class="inputbrand">
            <label for="inputbrand">ブランド*</label>
            <%= f.collection_select(:brand_id, Brand.all, :id, :name, {}, {class:"form-control", id:"inputbrand"}) %>
          </div>

          <div class="gearmodel">
            <label for="gearmodel">ギアのモデル名*</label>
            <%= f.text_area :gearmodel, class:"form-control", id:"gearmodel", placeholder:"ギアのモデル（必須 40文字まで)", maxlength:"40" %>
          </div>

          <div class="price">
            <label for="price">購入価格(円)</label>
            <%= f.number_field :price, class:"form-control", id:"price", placeholder:"例）¥10,000", max:"1000000" %>
          </div>

          <div class="url">
            <label for="url">購入先URL等</label>
            <%= f.url_field :url, class:"form-control", id:"url", placeholder:"https://" %>
          </div>

          <div class="row">
            <div class="col">
              <label for="purchase_date">所有開始時期</label>
              <%= f.date_field :purchase_date, class:"form-control", id:"purchase_date" %>
            </div>
            <div class="col">
              <label for="release_date">所有終了時期</label>
              <%= f.date_field :release_date, class:"form-control", id:"release_date" %>
            </div>
          </div>

          <div class="geartext">
            <label for="geartext">ギアの説明*</label>
            <%= f.text_area :text, class:"form-control", id:"geartext", placeholder:"商品の説明（必須 1,000文字まで）例）2020年頃に1万円で購入したテントです。ポリコットン製で重量はありますが見た目に惚れて買いました。" ,rows:"7" ,maxlength:"1000" %>
          </div>
          <br>

          <div class="submitchange">
            <%= f.submit "更新する" , class:"btn btn-secondary btn-sm" %>
            <%= link_to 'もどる', post_path, class:"btn btn-sm btn-outline-secondary" %>
          </div>

        <% end %>

      </div>
    </div>
  </main>

<%= render "shared/footer" %>

app/views/posts/index.html.erb
  <%= render "shared/header" %>

  <main>
    <section class="text-center container-fluid bg-light">
      <div class='title-contents'>
        <div class="row py-lg-3">
          <div class="col-lg-9 col-md-12 mx-auto">
            <br>
            <h1 class="fw-light-ext">ギア好きキャンパーたちが集うCamp Pro</h1>
            <br>
            <p class="lead-ext">自慢のギアを他のキャンパーたちと共有しよう</p>
            <br>
          </div>
        </div>
      </div>
    </section>

    <section>
      <h4 class="text-center mt-2 py-3 bg-light border fw-bold">-最新ギア一覧-</h4>
      <div class="album py-3 bg-light">
        <%= render "shared/album" %>
        <br>
        <%= paginate @posts, theme: 'bootstrap-5', pagination_class: "pagination-sm flex-wrap justify-content-center" %>
      </div>
    </section>

    <section>
      <h4 class="text-center mt-2 py-3 bg-light border fw-bold">-人気ギア一覧-</h4>

      <div class="album py-3 bg-light">
        <div class="container">
          <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <% @posts_best.first(3).each do |post| %>
              <%= render "shared/albumdetail", post: post %>
            <% end %>
          </div>
        </div>
        <br>
      </div>
    </section>
  </main>

  <%= render "shared/footer" %>

app/views/posts/new.html.erb
<%= render "shared/header" %>

  <main>
    <div class="container-fluid text-center bg-light">
    <h4 class="text-center mt-2 py-3 bg-light">ギア新規登録</h4>

      <div class="col-lg-6 card mb-3 w-90 p-4 mx-auto shadow-sm">

        <%= form_with model: @post, id: 'new_post', local: true do |f| %>
          <%= render 'shared/error_messages', model: f.object %>

          <div id="previews"></div>
          <div class="img-upload">
            <div class="click-upload">
              <label for="gearimagepost">ギア画像</label>
              <%= f.file_field :image, class:"form-control", id:"gearimagepost" %>
            </div>
          </div>

          <div class="inputcategory">
            <label for="inputcategory">カテゴリー*</label>
            <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"form-control", id:"inputcategory"}) %>
          </div>

          <div class="inputbrand">
            <label for="inputbrand">ブランド*</label>
            <%= f.collection_select(:brand_id, Brand.all, :id, :name, {}, {class:"form-control", id:"inputbrand"}) %>
          </div>

          <div class="gearmodel">
            <label for="gearmodel">ギアのモデル名*</label>
            <%= f.text_area :gearmodel, class:"form-control", id:"gearmodel", placeholder:"例）タフスクリーン2ルームハウス/MDX+", maxlength:"40" %>
          </div>

          <div class="price">
            <label for="price">購入価格(円)</label>
            <%= f.number_field :price, class:"form-control", id:"price", placeholder:"例）¥10,000", max:"1000000" %>
          </div>

          <div class="url">
            <label for="url">購入先URL等</label>
            <%= f.url_field :url, class:"form-control", id:"url", placeholder:"https://" %>
          </div>

          <div class="row">
            <div class="col">
              <label for="purchase_date">所有開始時期</label>
              <%= f.date_field :purchase_date, class:"form-control", id:"purchase_date" %>
            </div>
            <div class="col">
              <label for="release_date">所有終了時期</label>
              <%= f.date_field :release_date, class:"form-control", id:"release_date" %>
            </div>
          </div>

          <div class="geartext">
            <label for="geartext">ギアの説明、使い方等*</label>
            <%= f.text_area :text, class:"form-control", id:"geartext", placeholder:"例）最大収容人数5人のツールームテント。家族4人でちょうどいいサイズ感。組み立ても簡単で頑張れば女性ひとりでも立てられる。" ,rows:"7" ,maxlength:"1000" %>
          </div>
          <br>

          <div class="submitchange">
            <%= f.submit "登録する" , class:"btn btn-secondary btn-sm" %>
            <%= link_to 'もどる', root_path, class:"btn btn-sm btn-outline-secondary" %>
          </div>

        <% end %>

      </div>
    </div>
  </main>

<%= render "shared/footer" %>

app/views/posts/search.html.erb
<%= render "shared/header" %> 

  <main>
    <div class="container-fluid bg-light">
      <div class="card w-90 p-0 mx-auto shadow-sm">
        <div class="card-body">
          <h4 class="text-center py-3 bg-light">検索結果</h4>

          <div class="album pt-3 bg-light">
            <%= render "shared/album" %>
            <br>
            <%= paginate @posts, theme: 'bootstrap-5', pagination_class: "pagination-sm flex-wrap justify-content-center" %>
          </div>

        </div>
      </div>
    </div>
  </main>

<%= render "shared/footer" %>

app/views/posts/show.html.erb
<%= render "shared/header" %>

  <main>
    <div class="container-fluid text-center py-3 bg-light">
      <div class="col-lg-6 card w-90 p-3 mx-auto shadow-sm">

        <h4 class="card-title"><%= @post.gearmodel %></h4>
        <p><small>
          <%= link_to @post.brand.name, "/posts/brand/#{@post.brand_id}", class:"text-muted" %> > 
          <%= link_to @post.category.name, "/posts/category/#{@post.category_id}", class:"text-muted" %>
        </small></p>

        <% if @post.image.present? %>
          <%= image_tag @post.image, class: "mx-auto rounded w-75 img-fluid" %>
        <% else %>
          <%= image_tag "nophoto.png", size:"300x200", class: "mx-auto rounded w-75 img-fluid" %>
        <% end %>

        <div class="mt-2">
          <%= link_to '', "https://twitter.com/share?hashtags=CampPro,キャンプ沼", title: 'Twitter', target: '_blank', class: 'fa-brands fa-twitter-square fa-2x text-decoration-none', style:'color:dodgerblue;' %>
          <%= link_to '', "http://line.me/R/msg/text/?=#{@post.user.nickname}さんのギアがシェアされました%0a#{request.url}%0ali", title: 'LINE', target: '_blank', class: 'fa-brands fa-line fa-2x text-decoration-none', style:'color:limegreen;' %>
          <%= link_to '', "http://www.facebook.com/sharer/sharer.php?#{request.url}", title: 'LINE', target: '_blank', class: 'fa-brands fa-facebook-square fa-2x text-decoration-none', style:'color:royalblue;' %>
        </div>

        <div class="card-body">
          <p class="card-title">オーナー：<%= link_to @post.user.nickname, user_path(@post.user.id), class:"text-muted" %>さん</p>
          <p class="card-text">ギアの説明：<%= @post.text %></p>
          <p class="card-text">参考URL：<%= @post.url %></p>
          <p class="card-text">ギアの購入価格：<%= number_to_currency(@post.price, unit:"円") %></p>
          <p class="card-text">所有開始時期：<%= @post.purchase_date %></p>
          <p class="card-text">所有終了時期：<%= @post.release_date %></p>
          <% if user_signed_in? && current_user.id == @post.user_id %>  
            <button type="button" class="btn btn-sm btn-outline-secondary">
              <%= link_to "編集", edit_post_path, method: :get, class:'text-reset' %>
            </button>
            <button type="button" class="btn btn-sm btn-outline-secondary">
              <%= link_to "削除", post_path, method: :delete, class:'text-reset' %>
            </button>
          <% end %>
        </div>
        
      </div>
    </div>

  <div class="container-fluid text-center pb-1 bg-light">
    <div class="col-lg-6 card mb-3 w-90 p-4 mx-auto shadow-sm">
      <ul class="comments_lists" id="comments">
        <% @comments.each do |comment| %>
          <%= comment.text %> 

          <small>
            by
            <%= link_to comment.user.nickname, user_path(comment.user.id), class:"text-muted" %>さん 
            at
            <%= comment.created_at.to_s(:datetime_jp) %>
          </small>
          <br>
          <br>
        <% end %>
      </ul>
        <% if user_signed_in? %>  
          <%= form_with model: [@post, @comment], local: true do |f| %>
              <div class="form-group">
                <%= f.label :text, 'コメントする', class:'control-label' %>
                <%= f.text_area :text, id:'comment_text', class:'form-control', rows:"3", maxlength:"1000" %>
              </div>
              <br>
              <div class="row">
                <div class="col">
                  <%= f.submit '送信', class:"btn btn-secondary btn-sm" %>
                </div>
                  <p class="comment-warn">
                    <small class="text-muted">
                      相手のことを考え丁寧なコメントを心がけましょう。<br>
                      不快な言葉遣いなどは利用制限や退会処分となることがあります。
                    </small>
                  </p>
              </div>
          <% end %>
        <% end %>
      </div>
    </div>

  </main>

<%= render "shared/footer" %>